### ISSUE TITLE
Proposal for small code refactoring

### ISSUE THREAD

**Issue by vladkolodka** [evgenles/TelegramVkBot#1]
https://github.com/evgenles/TelegramVkBot/blob/da356ecf10683fefc6809714557fb3cd3100b8d8/Startup.cs#L27

Class "TelegramSender" could be converted to service and IConfiguration will be injected into that service to provide access to configuration.
Instead of creating an instance and passing parameters directly.

Also, I think it could be better if you move config keys to constants.
Or you can create configuration section and bind it to object and access this configuration item through object properties.

**Comment by averenium** [comment]
Moved token configs into class
https://github.com/evgenles/TelegramVkBot/blob/68af295a5d228902f098e00323bbe2c556e8c643/TokenConfig.cs#L8-L13
Removed passed parameters directly
https://github.com/evgenles/TelegramVkBot/blob/68af295a5d228902f098e00323bbe2c556e8c643/Startup.cs#L27
Now resolving parameters in Sender
https://github.com/evgenles/TelegramVkBot/blob/68af295a5d228902f098e00323bbe2c556e8c643/TelegramSender.cs#L51-L53
