### ISSUE TITLE
Possible unsafe behavior

### ISSUE THREAD

**Issue by vladkolodka** [evgenles/TelegramVkBot#2]
https://github.com/evgenles/TelegramVkBot/blob/da356ecf10683fefc6809714557fb3cd3100b8d8/TelegramSender.cs#L259

https://github.com/evgenles/TelegramVkBot/blob/da356ecf10683fefc6809714557fb3cd3100b8d8/TelegramSender.cs#L248

Microsoft says:
> DO NOT access any finalizable objects in the finalizer code path, because there is significant risk that they will have already been finalized.

Bool parameter in `Dispose(bool)` should be used to prevent `Dispose` calls on objects that may be already finalized.

See more info in [docs](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern#finalizable-types).

**Comment by averenium** [comment]
Fixed disposing
https://github.com/evgenles/TelegramVkBot/blob/68af295a5d228902f098e00323bbe2c556e8c643/TelegramSender.cs#L332-L347
